baseURL           = "http://smoothengineer.com/"
languageCode      = "en-us"
title             = "Smooth Engineer"
disqusShortname   = ""
googleAnalytics   = ""

# GLOBALS
[params]
    description = "visuallydefine by avimehenwal"         # Max 160 characters show in search
    author      = "Avi Mehenwal"
    author_url  = "https://avimehenwal.in/"
    theme       = "brown"   # red, pink, purple,deep-purple,indigo,blue,cyan,teal, green,yelow,amber,orange,grey,brown
    hover       = "yellow"
    nav_bg      = "w3-teal"
    banner      = "VideoCameraHeadReadingBook3-300x268.jpg"  #"vd-banner-1.svg"
    subscribe   = "http://eepurl.com/dlqpQX"
