baseURL           = "http://smoothengineer.com/"
languageCode      = "en-us"
title             = "Smooth Engineer"
disqusShortname   = ""
googleAnalytics   = ""

# GLOBALS
[params]
    logo        = "&sect;&Mu;&Phi;&thetasym;&Tau;&Eta; &sum;&eta;g&iexcl;&Pi;&Xi;&Epsilon;&Gamma;"
    description = "visuallydefine by avimehenwal"         # Max 160 characters show in search
